{% set name = "tinyrpc" %}
{% set version = "1.0.1" %}
{% set sha256 = "4572c9d63b056b5eb24bae5e0894115fe6b5c3fa314851d9df439c7d3f8e9d2b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - six
  run:
    - python
    - six

test:
  imports:
    - tinyrpc
    - tinyrpc.dispatch
    - tinyrpc.protocols
    - tinyrpc.server
    - tinyrpc.transports

about:
  home: http://github.com/mbr/tinyrpc
  license: MIT
  summary: 'A small, modular, transport and protocol neutral RPC library that, among other things, supports JSON-RPC and zmq.'
  license_family: MIT
  # license_file: LICENSE # https://github.com/mbr/tinyrpc/pull/44
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'

extra:
  recipe-maintainers:
    - mariusvniekerk
