travis:
  secure:
    BINSTAR_TOKEN: Uf0nneJD1PscrYRAuETc+Z6GCwM3TXS+3iVlvhtKe0aOHh9OOZ8/bA/2VTFL3ap2jKqEqG8cDdW1ibbNDqk9PpaeI3oh5jYMHWV603LC9rvuBFBFoLqxBnU+u//CnTl+O2F45mlc8/RSVW65FwJuRJRVL8HyG/PNrjlv9vrKsJDdFj+RfzkzqbewxOf4Vwbe3zlnL3bSAaveCHf1chlIhnUyQIgV8IB6sPKSjtBtcunPVQIoRy9Qrn/44tXIthPFteq8GBY+U3Yr9znjOkHpH0cExyP7VECLpK2Y74vwfb8uxJnp0SAv0nmws6CLbswFIicDIO9ZFl8ynfdnCdGIduhGQA5M0qKw5we+5u9v+9EK+wRHolw/gAyvtJoHseAebg+Cp7qxAImvuEuEXnjW1+/bFyY+0A3gv5wtlRW83+KIOQeYp8YIiMXFBZC+dyIFFkU3V5n6fI15uwPWABGNqQLAWwKUR+UeKKCQmOxc+psdiylbEcQVaTXqj7jGMSKLCLXhE0ChSGBNgFVwDiBFQI7bQegejZi/OFaGxxIEPntbLku3k+al8g3TAK8Boy9AcS9HteY4euxdhsQWNPIIe8yJML2brWx3H6B5QGbQAu6KQDzpiUXJM0svBjjGEwRmV6oOJ62FnKfc4f/Mt+HcNO3DOdBmXbnMbFZIhZdAUKI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
