travis:
  secure:
    BINSTAR_TOKEN: eJDk3qqG0+I160HEZm5//Ku1ZWZUZQ8Ojou5NmsVU0uUDIyqxssdYs2wzesQmogVqlv9Amoy7ZWRt87nsZYH+2tPGCjN4UXUKQnGh09hgM+ld8/iB0AQITsyS3Bns2T67nNHxyJ2WOsAu09ipEyPsx7B3j+HNEjCBRkJV0Cze90gMZe1a2aP3C3BV6rkCIRVT09LUBXkMvbCo9u1AuGZArJOXVkX975zu2m+NzUR6xXF6PnIHp/Obvhu37G1QcUDFtVVsgrygjhgLNlPaDUS3a8HloWUlp8ghdLPCNo99r0DXiKOyyOdSpZKP9qeBF7oNPpCD646QVMx9OIXmHQJO0MC7uy6A0YgV0vAcJsS6Y29XV4cQ4jmI4OFUxLXC02xHhhhwOHqDT6IpP75QzexR++HjdbMcffmjJs0jKw3aLQLxuXNiiK6GYKqpUa2wUdBFqZIOWV4pulMnscM0Qv2EuGK3j1uGQCX+JBKYyWno3t6BGqCTsiJIxXuyOBn4dwd916pen7qQjRBubMBTGmlw1R4XNRFmcuYAVjOkrga9Yg6B5FL+6HhpWVq8MPe4VLcFTrBn597TJUHWoEMPfKsBGaJitD+/sDEEfC/rL98prwiBzJLIT6ZVOMAQmTtwhI6ItjxPpDnMiixjA4zMcNkB2A1+hH6hna0XhxtTR2BjaY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
