travis:
  secure:
    BINSTAR_TOKEN: T235LZLp4UkWPTT8gUmmYHkxnESveeEEhHmQBK8oR9nlG2eXYm6CzGLqoOUh0eRjFEAFVv4cmjeYXuZZWm9oGQCcgkz7sMWNyVkMB0vmR0BHoMywccm56H6CnkG46VCz+4O8lcOY4qIMhPXP5+CV7Tssz2B7+D2kB15a4YVSHGgZ78SO65V3NkIw/UNTzen3BWhBXrNFxgeKhEl/K3wbemYdemdPBGsBquUEjWn42qNKzKbmLxKFCkOtCbyeQMMBMIhQKBMyn4oWOZtjUROz6s2bny8v7EAVGnaKC5d61hqqmORfqzUYUh055MG13uZ2VSZZLHKfmjy0vlzplQsTGG8ooKWn83q3R8qj605XDe/V+yEUL+CgrMyKfMDsIwN74sVP8gSc4UQGiHzyGkjrzUVkras5vshZFYUbIijlvOjlYXlr2W6LA1dSBjKmqfdn2GABMFogoxJwUatNQiZqb8c3wSVj7OXk7/Gty0zCIzIWbcGTcDZtYpeVDyXum/+G72BZe3D4ALKBfQH/a7DvUiK9n6wpc2RAhfXWXF0pB24fNVy+0YnXASP4KOLdvlRWc5tMZQ3LJoi5SOoyrzGwrAjs21WfuB1iNmTzuAIvBW08agRrPQdWmNiKeV25mZH1gw6rCeb+Nc6PhSiE2wcBiVVFUC3stWzo1BE8jF09azU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
