travis:
  secure:
    BINSTAR_TOKEN: Xv52/AuZQ8v1SIQgFNl25+4glzdFmmiE7SDKmm4nNBLUOz1/vnwqp0MDkoPmCsp25gkTeMZGvoUslxKK9uXjruTxXN1eF4MAxDOeExqfys1ql349MgUviZ+VGRRilnvCvzauZMWIk1ZZ3te6vCXF1RJEVSYIm864ovHohN5RoYKMxPVx8EdsRsedhurJHzIu1j70vhQVJP8r2VpBSMTc3NtLIWYMKzXKTlw/zHMvHDU080+73bJO00b/7qnOg+AREwIKc2OcEIaZEPqXdu9+9kmeI3FQJJ3a5tYYNX9KoPfo3dUDLubuTVFqXyIyc0CbsX7GNP3ytIGjtR2j/t2JWddkyEmF0N/yhr/Z6rci1FTo1azLbKdD6XfOuFhWL/wOpqzNnyZUaNoMlV7LPC7BS3xLVDg1uWNKJoftMEweC3i5FdcAHCegFcGFAx19EPdpkIotHCGbwORHgTZTjlrlod7UsewXeQg6srqE22R2IgCYVwQs1BlEn83tOxHAGXzIOnJAt4MpjG/PUpCiiYK8Tu+2o1xpOzjw+uVQIzBp7dchfbALNHEWsJsZRYYvh2D7hL+8C34QFO2NN1oiDMsO5qSDbrckdvUQHv55FTKMZI86UQiFl5PjA6EVaop7YJEHhQDXpHgj2BYrbFfux2L0xFMP8hwK/J6lGbL0mGeiYsU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
